---
- name: Update and upgrade packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install UFW firewall
  apt:
    name: ufw
    state: present

- name: Allow only SSH and HTTP/S traffic
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - 80
    - 443

- name: Enable UFW
  ufw:
    state: enabled

- name: Disable root SSH login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    backup: yes

- name: Restart SSH service
  service:
    name: ssh
    state: restarted
