- name: Add GPG key
  apt_key:
    url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    state: present


- name: Add Wazuh repository
  apt_repository:
    repo: "deb https://packages.wazuh.com/4.x/apt/ stable main"
    state: present

- name: Install Wazuh Agent
  apt:
    name: wazuh-agent
    state: present
    update_cache: yes

- name: Configure Wazuh Agent Manager IP
  lineinfile:
    path: /var/ossec/etc/ossec.conf
    regexp: '<address>.*</address>'
    line: "<address>{{ wazuh_manager_ip }}</address>"

- name: Enable and start agent
  systemd:
    name: wazuh-agent
    enabled: yes
    state: started


- name: Install Filebeat
  apt:
    name: filebeat
    state: present
    update_cache: yes

- name: Configure Filebeat output to Wazuh
  lineinfile:
    path: /etc/filebeat/filebeat.yml
    regexp: '^output.elasticsearch:'
    line: "output.logstash:\n  hosts: [\"{{ wazuh_manager_ip }}:5000\"]"

- name: Enable and start Filebeat
  systemd:
    name: filebeat
    enabled: yes
    state: restarted
